name = "OffPolicy"
uuid = "064fa28f-0d52-4680-88b2-3025b28a199f"
authors = ["Scott Jordan"]
version = "0.1.0"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
